language: python
python:
  - '2.7'
  - '3.5'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libenchant-dev redis-server
install: "pip install -r requirements.txt -r dev-requirements.txt pytest pytest-cov mock codeclimate-test-reporter"